version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        progress: plain
    container_name: pdf-backend
    ports:
      - '8000:8000'
    environment:
      - OLLAMA_SERVER_URL=${OLLAMA_SERVER_URL:-http://host.docker.internal:11434}
      - VECTOR_DB_DIR=/app/vector_database
      - UPLOADED_DOCS_DIR=/app/uploaded_docs
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pdf-frontend
    ports:
      - '8501:8501'
    environment:
      - BACKEND_URL=http://pdf-backend:8000
    depends_on:
      backend:
        condition: service_started
    restart: always
